[project]
name = "vacancies-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.21.0",
    "aiokafka>=0.12.0",
    "loguru>=0.7.3",
    "python-dotenv>=1.1.1",
]
